# Generated by Django 5.0.7 on 2024-07-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_expensesplit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='payer',
            new_name='user_id',
        ),
        migrations.DeleteModel(
            name='ExpenseSplit',
        ),
    ]
