# Generated by Django 5.0.7 on 2024-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='NUll', max_length=12),
        ),
    ]
